config/routes.rb
Rails.application.routes.draw do

  get 'machines/new'

  get '/' => 'welcome#index'
  get 'welcome/index'

  root :to => 'welcome#index'
  
  get 'login' => 'session#new'
  post 'login' => 'session#create'
  delete 'logout' => 'session#destroy'

  get 'session/new'

  get 'users/new'
  get 'users/list'
  get 'users/edit'
  get 'users/update'
  get 'users/show'

  get 'branchs/new'
  get 'branchs/show'
  post 'branchs/show'
  get 'branchs/list'
  get 'branchs/delete'
  get 'branchs/edit'
  get 'branchs/update'

  get 'machines/new'
  get 'machines/show'

  get 'bilances/new'
  get 'bilances/show'

  match ':controller(/:action(/:id))(.:format)', :via => [:post]
  match ':controller(/:action(/:id))(.:format)', :via => [:get]

end

app/models/bilance.rb
class Bilance < ActiveRecord::Base
	belongs_to :machine
	validates_presence_of :date
	validates_presence_of :in
	validates_presence_of :out
	validates_numericality_of :in, :message=>"Pouze číslo"
	validates_numericality_of :out, :message=>"Pouze číslo"
end

app/models/branch.rb
class Branch < ActiveRecord::Base
	has_and_belongs_to_many :users, :uniq => true
	has_many :machines
	validates_presence_of :name
	validates_presence_of :address
end

app/models/machine.rb
class Machine < ActiveRecord::Base
	TYPE = ['VLT', 'Magic', 'Ruleta']
	belongs_to :branch
	has_many :bilances
	validates_presence_of :name
	validates_presence_of :category
end

app/models/user.rb
class User < ActiveRecord::Base
	has_and_belongs_to_many :branches, :uniq => true
	# has_secure_password
	validates_presence_of :name
	validates_presence_of :username
	validates_presence_of :password
	accepts_nested_attributes_for :branches, :reject_if => :all_blank, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionHelper

end

app/controllers/branchs_controller.rb
class BranchsController < ApplicationController
  	def new
  		@branch = Branch.new
  	end

  	def create

		    #@project = Project.new(params[:project])
		    #@project.users << User.find(current_user.id)
			#@user = @current_user
    	@branch = Branch.new(branch_params)
    	@branch.users << User.find(current_user.id)
    	if @branch.save
      		flash[:success] = "Úspěšné přidání"
      		redirect_to :action => 'show', :id => @branch
      		return
    	else
      		flash[:danger] = "Přidání nebylo úspěšné"
      		flash[:color]= "invalid"
    	end
    	render "new"
    end

    def list
    	@branches = Branch.all
    end

    def show
    	@branch = Branch.find(params[:id])
    	@users = @branch.users
    	@others = User.all - @users
    	@machines = @branch.machines
    end

    def removeUser
    	@branch = Branch.find(params[:id])
    	@branch.users.delete(User.find(params[:user_id]))
    	redirect_to :action => 'show', :id => @branch
    end

	def addUser
    	@branch = Branch.find(params[:id])
    	@branch.users << User.find(params[:user_id])
    	redirect_to :action => 'show', :id => @branch
    end    

    def delete
   		Branch.find(params[:id]).destroy
   		redirect_to :controller => 'user', :action => 'show', :id => current_user.id
	end

	def edit
		@branch = Branch.find(params[:id])
	end

	def update
  	@branch = Branch.find(params[:branch][:id])
  	if @branch.update(branch_params)
  		flash[:success] = "Provozovna aktualizována"
    	redirect_to :action => 'show', :id => @branch
  	else
  		flash[:danger] = "Provozovna nebyla aktualizována"
      	render :edit
  	end
  end

    private
  	def branch_params
    	params.require(:branch).permit(:name, :address, :city)
  	end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
	def new
		@branch = Branch.find(params[:branch_id])
		@machine = Machine.new
	end

	def create
		@branch = Branch.find(params[:machine][:branch_id])
		@machine = Machine.new(machine_params)
		if @machine.save
			@branch.machines << @machine
			flash[:success] = "Úspěšné přidání"
      		redirect_to :action => 'show', :id => @machine
		else
			flash[:danger] = "Přidání nebylo úspěšné"
      		flash[:color]= "invalid"
		end
	end

	def show
		@machine = Machine.find(params[:id])
		@bilances = @machine.bilances
	end

	private
  	def machine_params
    	params.require(:machine).permit(:name, :category)
  	end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  	def new
  	end

  	def create
  		@user = User.find_by(username: params[:session][:username], password:params[:session][:password])
  		if @user #&& @user.authenticate(params[:session][:password])
  			log_in @user
        #flash[:success] = 'Úspěch'
  			redirect_to :controller => 'users', :action => 'show', :id => @user
  		else
  			flash[:error] = 'Přihlášení nebylo úspěšné'
  			render 'new'
  		end
  	end

  	def destroy
  		log_out
    	redirect_to root_path
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	def new
  		@user = User.new
  	end
  	def create
    	@user = User.new(user_params)
    	if @user.save
      		flash[:success] = "Úspěšné přidání"
      		redirect_to :action => 'show', :id => @user
      		return
    	else
      		flash[:danger] = "Přidání nebylo úspěšné"
      		flash[:color]= "invalid"
    	end
    	render "new"
  	end

  	def show
  		@user = User.find(params[:id])
  		@branches = @user.branches
  	end

  	def delete
   		User.find(params[:id]).destroy
   		redirect_to :action => 'list'
	  end

	def list
		@users = User.all
	end

	def edit
		@user = User.find(params[:id])
	end

	def login
		@user = User.find(params[:id])
	end

	def update
  	@user = User.find(params[:user][:id])
  	if @user.update(user_params)
  		flash[:success] = "Profil aktualizován"
    	redirect_to :action => 'show', :id => @user
  	else
      render :edit
  	end
  end

	private
  	def user_params
    	params.require(:user).permit(:username, :name, :password, :email, :phone, :address, :city, :birth_date)
  	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
    	{ success: "alert-success", error: "alert-danger", danger: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  	end

  	def flash_messages(opts = {})
    	flash.each do |msg_type, message|
	      	concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: "alert") do 
              concat content_tag(:button, raw('&times;'), class: "close", data: { dismiss: 'alert' }, aria: {label: 'Close'})
	            concat message 
	        end)
    	end
    	nil
  	end
end

app/helpers/branchs_helper.rb
module BranchsHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/session_helper.rb
module SessionHelper
	def log_in(user)
    	session[:user_id] = user.id
  	end

  	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
    	!current_user.nil?
  	end

  	def log_out
    	session.delete(:user_id)
    	@current_user = nil
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/branchs/edit.html.erb
<% @page_title = "Editace provozovny" %>
<div class="Edit_branch">
  <div class="page-header">
    <h1>Editace údajů provozovny</h1>
  </div>
  <%= form_for(:branch, :url => {:controller => 'branchs', :action => 'update'}) do |f| %>
    <div class="form-group">
      <%= f.text_field :id, :class => "form-control", :value => @branch.id, :type => "text", :style => "visibility:hidden"%>
    </div>
    <div class="form-group">
      <label for="nameInput">Název:</label>
      <%= f.text_field :name, :class => "form-control", :value => @branch.name, :type => "text" %> 
      <span class="label label-warning">Povinný údaj</span>
    </div>
    <div class="form-group">
      <label for="nameInput">Ulice:</label>
      <%= f.text_field :address, :class => "form-control", :value => @branch.address, :type => "text" %> 
      <span class="label label-warning">Povinný údaj</span>
    </div>
    <div class="form-group">
      <label for="nameInput">Město:</label>
      <%= f.text_field :city, :class => "form-control", :value => @branch.city, :type => "text" %> 
      <span class="label label-warning">Povinný údaj</span>
    </div>
    <%= f.submit :Aktualizovat, :class => "btn btn-success" %> <%= link_to "Zrušit", :back, :class => "btn btn-default" %>
  <% end %>
</div>

app/views/branchs/list.html.erb
<% @page_title = "Provozovny" %>
<div class="Branch">
  <div class="page-header">
    <h1>Provozovny</h1>
  </div>
  <%= link_to "Přidat provozovnu", {:controller => 'branchs', :action => 'new'}, :class => "btn btn-success" %>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Název</th>
        <th>Adresa</th>
        <th>Město</th>
        <th>Akce</th>
      </tr>
    </thead>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td><%= branch.address %></td>
        <td><%= branch.city %></td>
        <td><%= link_to "Zobrazit", {:action => 'show', :id => branch.id}, :class => 'btn btn-default' %>
            <%= link_to "Upravit", {:action => 'edit', :id => branch.id}, :class => 'btn btn-default' %>
            <%= link_to "Smazat", {:action => 'delete', :id => branch.id}, :class => 'btn btn-danger', data: { confirm: "Opravdu?" } %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/branchs/new.html.erb
<% @page_title = "Nová provozovna" %>
<div class="branches_form">
  <div class="page-header">
    <h1>Nová provozovna</h1>
  </div>
  <div class="span4">
    <%= form_for(:branch, :url => {:controller => 'branchs', :action => 'create'}) do |f| %>
      <div class="form-group">
        <label for="nameInput">Název:</label>
        <%= f.text_field :name, :class => "form-control", :placeholder => "Provozovna 1", :type => "text" %> 
        <span class="label label-warning">Povinný údaj</span>
      </div>
      <div class="form-group">
        <label for="nameInput">Adresa:</label>
        <%= f.text_field :address, :class => "form-control", :placeholder => "Příčná 123", :type => "text" %> 
        <span class="label label-warning">Povinný údaj</span>
      </div>
      <div class="form-group">
        <label for="nameInput">Město:</label>
        <%= f.text_field :city, :class => "form-control", :placeholder => "Montreal", :type => "text" %> 
        <span class="label label-warning">Povinný údaj</span>
      </div>
      <%= f.submit :Přidat, :class => "btn btn-success" %>
    <% end %>
  </div>
  <% if @branch.errors.any? %>
    <ul class="Add_Errors">
    <% for message_error in @branch.errors.full_messages %>
      <li><%= flash_messages %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/branchs/show.html.erb
<% @page_title = "Provozovna" %>
<div class="Branch">
  <div class="page-header">
    <h1>Detail provozovny <%= link_to "Editovat", {:action => 'edit', :id => @branch.id}, :class => "btn btn-default" %>
  <%= link_to "Smazat", {:action => 'delete', :id => @branch.id}, data: { confirm: "Opravdu smazat provozovnu?" }, :class => "btn btn-danger" %></h1>
  </div>
  <address>
    <strong><%= @branch.name %></strong><br>
    <%= @branch.address %><br>
    <%= @branch.city %><br>
  </address>

  <div class="page-header">
    <h3>Stroje <%= link_to "Přidat", {:controller => 'machines', :action => 'new', :branch_id => @branch.id}, :class => "btn btn-success" %></h3>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Název</th>
        <th>Kategorie</th>
        <th>Akce</th>
      </tr>
    </thead>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= machine.name %></td>
        <td><%= machine.category %></td>
        <td><%= link_to "Zobrazit", {:controller => 'machines',:action => 'show', :id => machine.id}, :class => 'btn btn-default' %>
            <%= link_to "Upravit", {:controller => 'machine',:action => 'edit', :id => machine.id}, :class => 'btn btn-default' %>
      </tr>
    <% end %>
  </table>


  <div class="page-header">
    <h3>Provozní</h3>
  </div>

  <div class="page-header">
    <h4>Přiřazení provozní</h4>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Jméno</th>
        <th>Uživatelské jméno</th>
        <th>Email</th>
        <th>Město</th>
        <th>Akce</th>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.city %></td>
        <td><%= link_to "Zobrazit", {:controller => 'users',:action => 'show', :id => user.id}, :class => 'btn btn-default' %>
            <%= link_to "Upravit", {:controller => 'users',:action => 'edit', :id => user.id}, :class => 'btn btn-default' %>
            <%= link_to "Odebrat", {:controller => 'branchs',:action => 'removeUser', :id => @branch.id, :user_id => user.id}, :class => 'btn btn-warning' %></td>
      </tr>
    <% end %>
  </table>

  <div class="page-header">
    <h4>Nepřiřazení provozní</h4>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Jméno</th>
        <th>Uživatelské jméno</th>
        <th>Email</th>
        <th>Město</th>
        <th>Akce</th>
      </tr>
    </thead>
    <% @others.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.city %></td>
        <td><%= link_to "Zobrazit", {:controller => 'users',:action => 'show', :id => user.id}, :class => 'btn btn-default' %>
            <%= link_to "Upravit", {:controller => 'users',:action => 'edit', :id => user.id}, :class => 'btn btn-default' %>
            <%= link_to "Přidat", {:controller => 'branchs',:action => 'addUser', :id => @branch.id, :user_id => user.id}, :class => 'btn btn-success' %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  	<title>TipgamesEvidence</title>
	  	<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  	<link href="<%= stylesheet_url('bootstrap.min') %>" rel="stylesheet">
	  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  	<%= csrf_meta_tags %>
	</head>
	<body>
		<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
	    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
	    <script src="<%= javascript_url('bootstrap.min') %>"></script>
	    <!-- Main body -->
	    <nav class="navbar navbar-default navbar-static-top">
		  	<div class="container-fluid">
			    <div class="navbar-header">
			      	<a class="navbar-brand" href="#">
			        	<img alt="Tipgames" src="<%= image_url('logo_small.png') %>">
			      	</a>
			    </div>

			    <div class="nav navbar-nav navbar-left">
			    	<%= link_to 'Provozní', users_list_path, :class => "btn btn-default navbar-btn" %>
			        <%= link_to 'Provozovny', branchs_list_path, :class => "btn btn-default navbar-btn" %>	
			    </div>

			    <div class="nav navbar-nav navbar-right">
			    	<% if logged_in? %>
			    		<%= link_to "Můj profil", {:controller => 'users',:action => 'show', :id => current_user.id}, :class => "btn btn-success navbar-btn" %>
						<%= link_to "Odhlásit", logout_path, method: :delete, :class => "btn btn-default navbar-btn" %>
					<% else %>
						<%= link_to "Přihlášení", login_path, :class => "btn btn-success navbar-btn" %>
				      	<%= link_to "Registrace", users_new_path, :class => "btn btn-default navbar-btn" %>
					<% end %>
			      	
			     </div>
			 </div>
		</nav>
		<div class="container">
			
		 	<%= flash_messages %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/machines/new.html.erb
<% @page_title = "Nový stroj" %>
<div class="machines_form">
	<div class="page-header">
	    <h1>Nový stroj</h1>
	</div>
	<div class="span4">
	    <%= form_for(:machine, :url => {:controller => 'machines', :action => 'create'}) do |f| %>
	    	<div class="form-group">
		        <label for="nameInput">Typ:</label>
		        <%= f.select :category, Machine::TYPE, {}, {:class => "form-control"} %> 
		        <span class="label label-warning">Povinný údaj</span>
		    </div>
	      <div class="form-group">
	        <label for="nameInput">Název:</label>
	        <%= f.text_field :name, :class => "form-control", :placeholder => "Magic 1", :type => "text" %> 
	      </div>
	      <%= f.submit :Přidat, :class => "btn btn-success" %>
	      <div class="form-group" style = "visibility:hidden">
		        <label for="nameInput">Id:</label>
		        <%= f.text_field :branch_id, :class => "form-control", :value => @branch.id, :style => 'visibility:hidden' %> 
	      	</div>
	    <% end %>
  	</div>
  	<% if @machine.errors.any? %>
    	<ul class="Add_Errors">
	    	<% for message_error in @machine.errors.full_messages %>
	    		<li><%= flash_messages %></li>
	    	<% end %>
    	</ul>
  	<% end %>
</div>

app/views/machines/show.html.erb
<% @page_title = "Detail stroje" %>
<div class="Machine">
  <div class="page-header">
    <h1>Detail stroje <%= link_to "Editovat", {:action => 'edit', :id => @machine.id}, :class => "btn btn-default" %>
  <%= link_to "Smazat", {:action => 'delete', :id => @machine.id}, data: { confirm: "Opravdu smazat stroj?" }, :class => "btn btn-danger" %></h1>
  </div>
  <address>
    <strong><%= @machine.name %></strong><br>
    <%= @machine.category %>
  </address>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Datum</th>
        <th>In</th>
        <th>Out</th>
        <th>Akce</th>
      </tr>
    </thead>
    <% @bilances.each do |bilance| %>
      <tr>
        <td><%= bilance.date %></td>
        <td><%= bilance.in %></td>
        <td><%= bilance.out %></td>
        <td><%= link_to "Upravit", {:controller => 'users',:action => 'edit', :id => user.id}, :class => 'btn btn-default' %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/session/new.html.erb
<% @page_title = "Přihlášení" %>
<div class="login_form">
  <div class="page-header">
    <h1>Přihlášení</h1>
  </div>
  <div class="span4">
  	<%= form_for(:session, :url => {:controller => 'session', :action => 'create'}) do |f| %>
  		<div class="form-group">
	        <label for="nameInput">Uživatelské jméno:</label>
	        <%= f.text_field :username, :class => "form-control", :placeholder => "", :type => "text" %>
    	</div>
    	<div class="form-group">
	        <label for="nameInput">Heslo:</label>
	        <%= f.text_field :password, :class => "form-control", :placeholder => "", :type => "password" %> 
      	</div>
	    <%= f.submit :Přihlásit, :class => "btn btn-success" %>
	<% end %>
  </div>
</div>

app/views/users/edit.html.erb
<% @page_title = "Edit user" %>
<div class="Edit_user">
  <div class="page-header">
    <h1>Editace údajů</h1>
  </div>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'update'}) do |f| %>
    <div class="form-group">
      <%= f.text_field :id, :class => "form-control", :value => @user.id, :type => "text", :style => "visibility:hidden"%>
    </div>
    <div class="form-group">
      <label for="nameInput">Jméno:</label>
      <%= f.text_field :name, :class => "form-control", :value => @user.name, :type => "text" %> 
      <span class="label label-warning">Povinný údaj</span>
    </div>
    <div class="form-group">
      <label for="nameInput">Uživatelské jméno:</label>
      <%= f.text_field :username, :class => "form-control", :value => @user.username, :type => "text" %> 
      <span class="label label-warning">Povinný údaj</span>
    </div>
    <div class="form-group">
      <label for="nameInput">Heslo:</label>
      <%= f.password_field :password, :class => "form-control", :value => @user.password, :type => "password" %> 
      <span class="label label-warning">Povinný údaj</span>
    </div>
    <div class="form-group">
      <label for="nameInput">Email:</label>
      <%= f.text_field :email, :class => "form-control", :value => @user.email, :type => "email" %>
    </div>
    <div class="form-group">
      <label for="nameInput">Telefon:</label>
      <%= f.text_field :phone, :class => "form-control", :value => @user.phone, :type => "tel" %>
    </div>
    <div class="form-group">
      <label for="nameInput">Datum narození:</label>
      <%= f.text_field :birth_date, :class => "form-control", :value => @user.birth_date, :type => "date" %>
    </div>
    <div class="form-group">
      <label for="nameInput">Ulice:</label>
      <%= f.text_field :address, :class => "form-control", :value => @user.address, :type => "text" %> 
    </div>
    <div class="form-group">
      <label for="nameInput">Město:</label>
      <%= f.text_field :city, :class => "form-control", :value => @user.city, :type => "text" %> 
    </div>
     <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= f.submit :Aktualizovat, :class => "btn btn-success" %>
  <% end %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

app/views/users/list.html.erb
<% @page_title = "User" %>
<div class="User">
  <div class="page-header">
    <h1>Provozní</h1>
  </div>
  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Jméno</th>
        <th>Uživatelské jméno</th>
        <th>Email</th>
        <th>Město</th>
        <th>Akce</th>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.city %></td>
        <td><%= link_to "Zobrazit", {:action => 'show', :id => user.id}, :class => 'btn btn-default' %>
            <%= link_to "Upravit", {:action => 'edit', :id => user.id}, :class => 'btn btn-default' %>
            <%= link_to "Smazat", {:action => 'delete', :id => user.id}, :class => 'btn btn-danger', data: { confirm: "Opravdu?" } %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<% @page_title = "Registrace" %>
<div class="sign_form">
  <div class="page-header">
    <h1>Registrace</h1>
  </div>
  <div class="span4">
    <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
      <div class="form-group">
        <label for="nameInput">Jméno:</label>
        <%= f.text_field :name, :class => "form-control", :placeholder => "Jan Novák", :type => "text" %> 
        <span class="label label-warning">Povinný údaj</span>
      </div>
      <div class="form-group">
        <label for="nameInput">Uživatelské jméno:</label>
        <%= f.text_field :username, :class => "form-control", :placeholder => "novak1", :type => "text" %> 
        <span class="label label-warning">Povinný údaj</span>
      </div>
      <div class="form-group">
        <label for="nameInput">Heslo:</label>
        <%= f.password_field :password, :class => "form-control", :placeholder => "novakJeNejlepsi", :type => "password" %> 
        <span class="label label-warning">Povinný údaj</span>
      </div>
      <div class="form-group">
        <label for="nameInput">Email:</label>
        <%= f.text_field :email, :class => "form-control", :placeholder => "novak@novak.cz", :type => "email" %>
      </div>
      <div class="form-group">
        <label for="nameInput">Telefon:</label>
        <%= f.text_field :phone, :class => "form-control", :placeholder => "123 123 123", :type => "tel" %>
      </div>
      <div class="form-group">
        <label for="nameInput">Datum narození:</label>
        <%= f.text_field :birth_date, :class => "form-control", :placeholder => "DD.MM.RRRR", :type => "date" %>
      </div>
      <div class="form-group">
        <label for="nameInput">Ulice:</label>
        <%= f.text_field :address, :class => "form-control", :placeholder => "Ulice 75", :type => "text" %> 
      </div>
      <div class="form-group">
        <label for="nameInput">Město:</label>
        <%= f.text_field :city, :class => "form-control", :placeholder => "Montreal", :type => "text" %> 
      </div>
      <%= f.submit :Registrovat, :class => "btn btn-success" %>
    <% end %>
  </div>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li><%= flash_messages %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/users/show.html.erb
<% @page_title = "Detail provozního" %>
<div class="User">
  <div class="page-header">
    <h1>Detail uživatele <%= link_to "Editovat", {:action => 'edit', :id => @user.id}, :class => "btn btn-default" %>
  <%= link_to "Smazat", {:action => 'delete', :id => @user.id}, data: { confirm: "Opravdu smazat uživatele?" }, :class => "btn btn-danger" %></h1>
  </div>
  <address>
    <strong><%= @user.username %> - <%= @user.name %></strong><br>
    <a href="mailto:#"><%= @user.email %></a><br>
    <%= @user.address %><br>
    <%= @user.city %><br>
    <abbr title="Telefon">Tel:</abbr> <%= @user.phone %>
</address>

  
  <div class="page-header">
    <h3>Provozovny <%= link_to "Přidat provozovnu", branchs_new_path, :class => "btn btn-default" %></h3>
  </div>
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Název</th>
          <th>Adresa</th>
          <th>Město</th>
          <th>Akce</th>
        </tr>
      </thead>
      <% @branches.each do |branch| %>
        <tr>
          <td><%= branch.name %></td>
          <td><%= branch.address %></td>
          <td><%= branch.city %></td>
          <td><%= link_to "Zobrazit", {:controller => 'branchs', :action => 'show', :id => branch.id}, :class => "btn btn-default" %>
              <%= link_to "Upravit", {:controller => 'branchs', :action => 'edit', :id => branch.id}, :class => "btn btn-default" %>
              <%= link_to "Smazat", {:controller => 'branchs', :action => 'delete', :id => branch.id}, :class => "btn btn-danger", data: { confirm: "Opravdu?" } %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Evidence Tipgames</h1>
  <p>Pro vstup do systému se, prosím, přihlašte.</p>
  <p><%= link_to "Přihlásit se", login_path, :class => "btn btn-success", :role => "button" %></p>
</div>